events/urls.py
from django.urls import path


from . views import (
    EventDashboardView,
    EventCreateView,
    EventListView,
    EventDetailView,
    OrganizerProfileVew,
    EventTrainerCreateView,
    # EventParticipantCreateView,
    EventDetailUpdateView,
    EventDeleteView,
    event_apply,
    EventParticipantList,
)

urlpatterns = [
    path('', EventDashboardView.as_view(), name='dashboard'),
    path('profile/', OrganizerProfileVew.as_view(), name="organizer_profile"),
    path('event_create/', EventCreateView.as_view(), name="event_create"),
    path('event_trainer/', EventTrainerCreateView.as_view(), name="event_trainer"),
    # path('event_participant/', EventParticipantCreateView.as_view(), name="event_participant"),
    path('event_list/', EventListView.as_view(), name="event_list"),
    path('participant_list/', EventParticipantList.as_view(), name="participant_list"),
    path('<slug:slug>/', EventDetailView.as_view(), name="detail"),
    path('<slug:slug>/update/', EventDetailUpdateView.as_view(), name="event_update"),
    path('<slug:slug>/apply/', event_apply, name="e_apply"),
    path('delete/<slug:slug>', EventDeleteView.as_view(), name="event_delete"),
]

pycamp/urls.py
from xml.dom.minidom import _in_document

from django.conf.urls import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('event/', include('events.urls')),
    path('', include('auth_module.urls')),
    path('@<username>/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('job/',include('jobpost.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models/event_participant.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.postgres.fields import JSONField

from userprofile.models import PersonalProfile
from events.models.event_details import EventDetail
from events.models.event_participant_queryset import EventParticipantQuerySet


class EventParticipantManager(models.Manager):
    """
        To find all participant list of the event;
        To find selected participant list of the event;
        To find paid participant list of the event;
    """
    def get_queryset(self):
        """
            :return event participant queryset object
        """
        return EventParticipantQuerySet(self.model, using=self._db)

    def all_participant(self):
        """
            return all registerd participant list of the event
        """
        return self.get_queryset().all_participant()

    def selected_participant(self):
        """
            return selected participant list of the event
        """
        return self.get_queryset().selected_participant()

    def paid_participant(self):
        """
            return paid participant list of the event
        """
        return self.get_queryset().paid_participant()


class EventParticipant(models.Model):
    event_title = models.ForeignKey(EventDetail, on_delete=models.CASCADE, null=True)
    participant_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='event_participant',
        related_query_name='participant'
    )

    registration_complete = models.BooleanField(default=False)
    is_selection_pass = models.BooleanField(default=False)
    payment_confirmed = models.BooleanField(default=False)
    review_participant = JSONField(default={}, null=True, blank=True)
    rating_participant = JSONField(default={}, null=True, blank=True)
    confirmation_text = JSONField(default={}, null=True, blank=True)
    participant_status = models.BooleanField(default=True)

    # participant = EventParticipantManager()

events/models/event_trainer.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.postgres.fields import JSONField

from userprofile.models import PersonalProfile
from events.models.event_details import EventDetail
from events.models.event_trainer_queryset import EventTrainerQuerySet


class EventTrainerManager(models.Manager):
    """
        get event trainer details
    """

    def get_queryset(self):
        """
            return queryset
        """
        return EventTrainerQuerySet(self.model, using=self._db)

    def event_trainer(self):
        """
            return trainer list
        """
        return self.get_queryset().event_trainer()


class EventTrainer(models.Model):
    event_title = models.ForeignKey(EventDetail, on_delete=models.CASCADE, null=True)
    trainer = models.ForeignKey(
        PersonalProfile,
        on_delete=models.CASCADE,
        related_name='event_trainer',
        related_query_name='trainer'
    )
    rating = models.FloatField(default=0, max_length=10)
    status = models.BooleanField(default=True)

    # object = EventTrainerManager()

templates/event_templates/event_archive.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container-fluid">

    <!-- started event archive table -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Event List
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th>Event Title</th>
                            <th>Start date to End date</th>
                            <th>Details</th>
                            <th>Participants</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for obj in object_list %}
                        <tr>
                            <td><a href="{{ obj.get_absolute_url }}" class="test-success"><span class="btn text-dark">{{ obj.title }}</span></a></td>
                            <td><span class="text-success">{{ obj.start_date }}</span> to <span class="text-danger">{{ obj.end_date }}</span></td>
                            <td class="text-center">
                                <a href="{{ obj.get_absolute_url }}" class="btn btn-outline-success">Details</a>
                            </td>
                            <td><a href="{% url 'participant_list' %}" class="btn btn-outline-info">Participants</a></td>
                            <td>
                                <a href="{% url 'event_update' obj.slug %}" class="btn btn-outline-primary">Update</a>
                                <a href="{% url 'event_delete' obj.slug %}" class="btn btn-outline-danger"><span class="glyphicon glyphicon-trash">Delete</span></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <nav>
                        {% if is_paginated %}
                        <ul class="pagination">
                            <li class="page-item">
                                {% if page_obj.has_previous %}
                                <a class="page-link" href="/event/event_list?page={{ page_obj.previous_page_number }}">Prev</a>
                                {% endif %}
                            </li>
                            <li class="page-item active">
                                <button class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</button>
                            </li>
                            <li class="page-item">
                                {% if page_obj.has_next %}
                                <a class="page-link" href="/event/event_list?page={{ page_obj.next_page_number }}">Next</a>
                                {% endif %}
                            </li>
                        </ul>
                        {% endif %}
                    </nav>
                </div>
            </div>
        </div>
        <!--/.col-->
    </div>
    <!-- end event archive table -->

</div>
<!-- /.conainer-fluid -->
{% endblock %}

templates/event_templates/event_create.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Create <strong>event</strong>
            </div>
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="card-block">
                    {# {{ event_detail.as_p }}#}
                    {% if event_detail.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in event_detail.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <b>Event Details</b>
                    <hr/>

                    {% for field in event_detail.visible_fields %}
                    <div class="form-group row">
                        <label for="{{ field.auto_id }}" class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                        {% if event_detail.is_bound %}
                        {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% else %}
                        {% render_field field class="form-control is-valid" %}
                        {% endif %}
                        {% else %}
                        <div class="col-md-6">
                            {% render_field field class="form-control" %}
                        </div>
                        {% endif %}
                    </div><!-- end of event_details form -->
                    {% endfor %}
                    <hr/>
                </div>
                <div class="card-footer">
                    <button type="submit" name="save-event" class="btn btn-sm btn-primary" value="update"><i
                            class="fa fa-dot-circle-o"></i> Save
                    </button>
                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--/.row-->

{% endblock %}

templates/event_templates/event_dashboard.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid">

    <div class="row center col-sm 12">
        {% for obj in object_list %}
        <div class="col-sm-4 img-thumbnail" style="margin: 4px">
            <a href="{{ obj.get_absolute_url }}"><img src="{{ MEDIA_URL }}{{ obj.banner.url }}" alt="{{ obj.banner }}" class="img-responsive" width="550" height="250"></a>
            <h5>{{ obj.title }}<small> ({{ obj.start_date }})</small></h5>
            <a href="{{ obj.get_absolute_url }}" class="btn btn-info">View Detail</a>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

templates/event_templates/event_participant.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block content %}
<a href="{% url 'event_list' %}" class="btn btn-dark btn-lg">Event List</a><br/><!-- temporary button -->
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Create <strong>event</strong>
            </div>
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="card-block">
                    {# {{ form.as_p }}#}
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <b>Event Trainer</b>
                    <hr/>
                    {% for field in event_participant.visible_fields %}
                    <div class="form-group row">
                        <label for="{{ field.auto_id }}" class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                        {% if form.is_bound %}
                        {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% else %}
                        {% render_field field class="form-control is-valid" %}
                        {% endif %}
                        {% else %}
                        <div class="col-md-6">
                            {% render_field field class="form-control" %}
                        </div>
                        {% endif %}
                    </div><!-- end of event_details form -->
                    {% endfor %}
                </div>
                <div class="card-footer">
                    <button type="submit" name="save-event" class="btn btn-sm btn-primary"><i
                            class="fa fa-dot-circle-o"></i> Save
                    </button>
                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--/.row-->

{% endblock %}

templates/event_templates/event_participant_view.html
{% extends 'base/base.html' %}

{% block content %}
<a href="{% url 'event_create' %}" class="btn btn-dark btn-lg">Event Create</a><!-- temporary button -->
<div class="container-fluid">

    <!-- started event archive table -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Event List
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th>Event Title</th>
                            <th>Participant</th>
                            <th>Details</th>
                            <th>Details</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for obj in object_list %}
                        <tr>
                            <td><a href="#" class="test-success"><span class="btn text-dark">Something</span></a></td>
                            <td><span class="text-success">Some one</span></span></td>
                            <td class="text-center">
                                <a href="#" class="btn btn-outline-success">Details</a>
                            </td>
                            <td>
                                <a href="#" class="btn btn-outline-danger"><span class="glyphicon glyphicon-trash">Delete</span></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <nav>
                        <ul class="pagination">
                            <li class="page-item"><a class="page-link" href="#">Prev</a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">2</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">4</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!--/.col-->
    </div>
    <!-- end event archive table -->

</div>
<!-- /.conainer-fluid -->


<br/><hr/>

<ul>
{% for obj in obj_list %}
    <li>{{ obj }}</li>
{% endfor %}
</ul>

{% endblock %}

templates/event_templates/event_trainer.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block content %}
<a href="{% url 'event_list' %}" class="btn btn-dark btn-lg">Event List</a><br/><!-- temporary button -->
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Create <strong>event</strong>
            </div>
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="card-block">
                    {# {{ form.as_p }}#}
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <b>Event Trainer</b>
                    <hr/>
                    {% for field in event_trainer.visible_fields %}
                    <div class="form-group row">
                        <label for="{{ field.auto_id }}" class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                        {% if form.is_bound %}
                        {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% else %}
                        {% render_field field class="form-control is-valid" %}
                        {% endif %}
                        {% else %}
                        <div class="col-md-6">
                            {% render_field field class="form-control" %}
                        </div>
                        {% endif %}
                    </div><!-- end of event_details form -->
                    {% endfor %}
                </div>
                <div class="card-footer">
                    <button type="submit" name="save-event" class="btn btn-sm btn-primary"><i
                            class="fa fa-dot-circle-o"></i> Save
                    </button>
                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--/.row-->

{% endblock %}

templates/event_templates/event_update.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <div class="card-block">
            {# {{ event_detail.as_p }} #}
            {% if event_detail.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {% for error in event_detail.non_field_errors %}
            {{ error }}
            {% endfor %}
            </div>
            {% endif %}

            {% for field in event_detail.visible_fields %}
            <div class="form-group row">
            <label for="{{ field.auto_id }}" class="col-md-3 col-form-label">{{ field.label_tag }}</label>
            {% if event_detail.is_bound %}
            {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
            <div class="invalid-feedback">
            {{ error }}
            </div>
            {% endfor %}
            {% else %}
            {% render_field field class="form-control is-valid" %}
            {% endif %}
            {% else %}
            <div class="col-md-6">
            {% render_field field class="form-control" %}
            </div>
            {% endif %}
            </div><!-- end of event_details form -->
            {% endfor %}
            <hr/>
            <!--</div>-->
            <div class="card-footer">
            <button type="submit" name="save-event" class="btn btn-sm btn-primary" value="update"><i
            class="fa fa-dot-circle-o"></i> Save
            </button>
            <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
            </div>
            </form>
        </div>
    </div>
</div>
<!--/.row-->

{% endblock %}

templates/event_templates/eventdetail_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

templates/event_templates/organizer_profile.html
{% extends 'base/base.html' %}

{% block content %}

<h1>PROFILE</h1>

{% endblock %}

templates/event_templates/participant_list.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container-fluid">

    <!-- started event archive table -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Event List
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th>Event Title</th>
                            <th>Full Name</th>
                            <th>Details</th>
                            <th>IS DONE</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for participant in eventparticipant_list %}
                        <tr>
                            <td width="350"><a href="#" class="test-success"><span class="btn text-dark">{{ participant.event_title }}</span></a></td>
                            <td width="350"><span class="text-success">{{ participant.participant_id }}</span></span></td>
                            <td class="text-center">
                                <a href="#" class="btn btn-outline-success">Details</a>
                            </td>
                            <td width="500">
                                <a href="#" class="btn btn-outline-info"><span class="glyphicon glyphicon-trash">REG</span></a>
                                <a href="#" class="btn btn-outline-info"><span class="glyphicon glyphicon-trash">SELECTION</span></a>
                                <a href="#" class="btn btn-outline-info"><span class="glyphicon glyphicon-trash">PAYMENT</span></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <nav>
                        {% if is_paginated %}
                        <ul class="pagination">
                            <li class="page-item">
                                {% if page_obj.has_previous %}
                                <a class="page-link" href="/event/participant_list?page={{ page_obj.previous_page_number }}">Prev</a>
                                {% endif %}
                            </li>
                            <li class="page-item active">
                                <button class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</button>
                            </li>
                            <li class="page-item">
                                {% if page_obj.has_next %}
                                <a class="page-link" href="/event/participant_list?page={{ page_obj.next_page_number }}">Next</a>
                                {% endif %}
                            </li>
                        </ul>
                        {% endif %}
                    </nav>
                </div>
            </div>
        </div>
        <!--/.col-->
    </div>
    <!-- end event archive table -->

</div>
<!-- /.conainer-fluid -->

{% endblock %}

templates/event_templates/single_event.html
{% extends 'base/base.html' %}

{% block content %}

<img src="{{ MEDIA_URL }}{{ object.banner.url }}" alt="{{ object.banner }}" class="img-responsive img-thumbnail" width="1600" height="400">
<br /><br />
<a href="{% url 'e_apply' object.slug %}" class="btn btn-info">Apply</a><br/><br/>
<div class="container-fluid">
    <table>
        <h4>Event Details</h4>
        <hr/>
        <div class="row">
            <tr>
                <td>Title-</td>
                <td>{{ object.title }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Start Date-</td>
                <td>{{ object.start_date }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>End Date-</td>
                <td>{{ object.end_date }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Registration Deadline-</td>
                <td>{{ object.registration_deadline }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Description-</td>
                <td>{{ object.description }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Banner-</td>
                <td>{{ object.banner }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Audience Type-</td>
                <td>{{ object.audience_type }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Max Audience-</td>
                <td>{{ object.max_audience }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Venue-</td>
                <td>{{ object.venue }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Venue Coordinate-</td>
                <td>{{ object.venue_coordinate }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Region-</td>
                <td>{{ object.region }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Currency-</td>
                <td>{{ object.currency }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Registration Fee-</td>
                <td>{{ object.registration_fee }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Is open for all -</td>
                <td>{{ object.open_for_all }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Is open for all -</td>
                <td>{{ object.screening_process }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Registration process -</td>
                <td>{{ object.registration_process }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Payment process -</td>
                <td>{{ object.payment_process }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Additional fees -</td>
                <td>{{ object.additional_fees }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Review event host -</td>
                <td>{{ object.review_event_host }}</td>
            </tr>
        </div>
    </table><!-- end of event_detail -->
    <hr/>
    <table>
        <h4>Event Trainer</h4>
        <hr/>
        {% for obj in event_trainer %}
        <div class="row">
            <tr>
                <td>Trainer Name</td>
                <td>{{ obj.trainer }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Rating</td>
                <td>{{ obj.rating }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Status</td>
                <td>{{ obj.status }}</td>
            </tr>
        </div>
        {% endfor %}
    </table><!-- end of event_trainer -->
    <hr/>
    <table>
        <h4>Event Participant</h4>
        <hr/>
        {% for obj in event_participants %}
        <div class="row">
            <tr>
                <td>Participant Name -</td>
                <td>{{ obj.participant_id }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Is registration complete -</td>
                <td>{{ obj.registration_complete }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Is selection pass -</td>
                <td>{{ obj.is_selection_pass }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Payment confirmed -</td>
                <td>{{ obj.payment_confirmed }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Review Participant -</td>
                <td>{{ obj.review_participant }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Rating Participant -</td>
                <td>{{ obj.rating_participant }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Confirmation Text -</td>
                <td>{{ obj.confirmation_text }}</td>
            </tr>
        </div>
        <div class="row">
            <tr>
                <td>Participant Status -</td>
                <td>{{ obj.participant_status }}</td>
            </tr>
        </div>
        {% endfor %}
    </table><!-- end of event_trainer -->

    <div class="row">
        <div class="col-md-5"></div>
        <div class="col-md-7">
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg">Apply</button>
            </form>
        </div>
    </div><br/><br/>
</div>

{% endblock %}