events/urls.py
from django.urls import path


from . views import (
    EventDashboardView,
    EventCreateView,
    EventListView,
    EventDetailView,
    OrganizerProfileVew,
    EventTrainerCreateView,
    # EventParticipantCreateView,
    EventDetailUpdateView,
    EventDeleteView,
    event_apply,
    EventParticipantList,
)

urlpatterns = [
    path('', EventDashboardView.as_view(), name='dashboard'),
    path('profile/', OrganizerProfileVew.as_view(), name="organizer_profile"),
    path('event_create/', EventCreateView.as_view(), name="event_create"),
    path('event_trainer/', EventTrainerCreateView.as_view(), name="event_trainer"),
    # path('event_participant/', EventParticipantCreateView.as_view(), name="event_participant"),
    path('event_list/', EventListView.as_view(), name="event_list"),
    path('participant_list/', EventParticipantList.as_view(), name="participant_list"),
    path('<slug:slug>/', EventDetailView.as_view(), name="detail"),
    path('<slug:slug>/update/', EventDetailUpdateView.as_view(), name="event_update"),
    path('<slug:slug>/apply/', event_apply, name="e_apply"),
    path('delete/<slug:slug>', EventDeleteView.as_view(), name="event_delete"),
]

jobpost/urls.py
from django.urls import path

from . import views

app_name = 'jobpost'

urlpatterns=[
    path('',views.listView,name='index'),
    path('create/<int:id>/',views.createJobView, name="create"),
    path('detail/<int:id>/',views.detailJobView,name='detail'),
    path('edit/<int:id>/',views.updateView,name='edit'),
    path('delete/<int:id>/',views.deleteView,name='delete'),
    path('myjob/<int:id>/',views.myJobView,name='myjob'),
    path('apply/<int:id>/', views.jobApplyView, name='job_apply'),
    path('applied/',views.myAppliedJob,name='applied'),
    path('applicant/<int:id>/', views.myApplicantView, name='applicant'),
    path('applicant_list/<int:id>/',views.myApplicantList,name='applicantlist'),

]

pycamp/urls.py
from xml.dom.minidom import _in_document

from django.conf.urls import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('event/', include('events.urls')),
    path('', include('auth_module.urls')),
    path('@<username>/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('job/',include('jobpost.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobpost/models.py
from django.db import models
from userprofile.models import OrganizationProfile, PersonalProfile
# Create your models here.


class JobPostBasic(models.Model):
    organization_id = models.ForeignKey(OrganizationProfile,on_delete=models.CASCADE)
    job_title = models.CharField(max_length=256)
    salary_range = models.CharField(max_length=256)
    is_part_time = models.BooleanField(default=False)
    position = models.CharField(max_length=256)
    stack = models.TextField()
    vacancy = models.PositiveIntegerField()
    deadline = models.DateField()

    def __str__(self):
        return self.job_title


class JobPostDetails(models.Model):
    job_id = models.ForeignKey(JobPostBasic,on_delete=models.CASCADE)
    description = models.TextField()
    application_process = models.TextField()
    screening_details = models.TextField()


class JobApplicant(models.Model):
    job_id = models.ForeignKey(JobPostBasic,on_delete=models.CASCADE)
    applicant_id = models.ForeignKey(PersonalProfile,on_delete=models.CASCADE)
    selection_confirmation= models.BooleanField(default=False)
    call_for_interview = models.BooleanField(default=False)

jobpost/models/job_applicant.py
from django.db import models
from django.contrib.auth.models import User

from userprofile.models.personal_profile import PersonalProfile
from jobpost.models.job_post_basic import JobPostBasic
from jobpost.models.job_applicant_queryset import JobApplicantQuerySet


class JobApplicantManager(models.Manager):
    """
        Find Job applicants
    """

    def get_queryset(self):
        return JobApplicantQuerySet(self.model, using=self._db)

    def all_applicant(self,id):
        return self.get_queryset().all_applicant(id)

    def selected_applicant(self):
        return self.get_queryset().selected_applicant()

    def get_job_applicant(self,j_id,a_id):
        return self.get_queryset().get_job_applicant(j_id,a_id)

    def get_applicant_list(self,job_id):
        return self.get_queryset().get_applicant_list(job_id)

    def get_applied_job(self,user_id):
        return self.get_queryset().get_applied_job(user_id)


class JobApplicant(models.Model):
    job = models.ForeignKey(JobPostBasic,on_delete=models.CASCADE)
    applicant = models.ForeignKey(User,on_delete=models.CASCADE)
    selection_confirmation= models.BooleanField(default=False)
    call_for_interview = models.BooleanField(default=False)
    apply_status = models.BooleanField(default=False)

    objects = JobApplicantManager()

jobpost/models/job_applicant_queryset.py
from django.db import models


class JobApplicantQuerySet(models.QuerySet):
    """
        Details about job applicants
    """

    def all_applicant(self):
        return self.all()

    def selected_applicant(self):
        return self.filter(selection_confirmation=True)

    def get_job_applicant(self,j_id,a_id):
        return self.get(applicant_id=a_id,job_id=j_id)

    def get_applicant_list(self,job_id):
        return self.defer('applicant').filter(job_id=job_id)

    def get_applied_job(self,user_id):
        return self.defer('job').filter(applicant_id = user_id)

jobpost/models/job_post_basic.py
import uuid

from django.db import models
from django.contrib.auth.models import User

from jobpost.models.job_post_basic_queryset import JobPostQuerySet
from userprofile.models.organization_profile import OrganizationProfile


class JobPostBasicManager(models.Manager):
    """
        Find Job query with job title
    """

    def get_queryset(self):
        return JobPostQuerySet(self.model, using=self._db)

    def get_job_title(self):
        """
            Return Job title
        """

        return self.get_queryset().get_job_title()

    def get_my_job(self,id):
        print(id)
        return self.get_queryset().get_my_job(id)


class JobPostBasic(models.Model):
    organization = models.ForeignKey(User,on_delete=models.CASCADE)
    job_title = models.CharField(max_length=256)
    salary_range = models.CharField(max_length=256)
    is_part_time = models.BooleanField(default=False)
    position = models.CharField(max_length=256)
    stack = models.TextField()
    vacancy = models.PositiveIntegerField()
    deadline = models.DateField()
    status = models.BooleanField(default=True)
    guid = models.UUIDField(default=uuid.uuid4, editable=False)

    objects = JobPostBasicManager()

    def __str__(self):
        return self.job_title

jobpost/models/job_post_basic_queryset.py
from django.db import models


class JobPostQuerySet(models.QuerySet):
    """
        Detail about job post query set
    """

    def get_job_title(self):
        """
            Get all job post
        """

        return self.defer('job_title','vacancy', 'deadline','id').filter(status=True)

    def get_my_job(self,id):
        # return self.defer('job_title','id','organization_id').filter(organization_id=id,status=True)
        return self.defer('job_title','vacancy', 'deadline','id').filter(organization_id=id,status=True)

jobpost/models/job_post_detail.py
from django.db import models

from jobpost.models.job_post_basic import JobPostBasic


class JobPostDetails(models.Model):
    job = models.OneToOneField(JobPostBasic,on_delete=models.CASCADE)
    description = models.TextField()
    application_process = models.TextField()
    screening_details = models.TextField()

jobpost/forms.py
from django import forms

from .models.job_post_basic import JobPostBasic
from .models.job_post_detail import JobPostDetails


class JobPostBasicForm(forms.ModelForm):
    class Meta:
        model=JobPostBasic
        #fields = '__all__'
        fields = ["job_title", "salary_range", "is_part_time", "position", "stack", "vacancy", "deadline"]

class JobPostDetailsForm(forms.ModelForm):
    class Meta:
        model=JobPostDetails
        #fields = '__all__'
        fields = ["description", "application_process", "screening_details"]

jobpost/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.http import Http404
from  .models.job_post_basic import JobPostBasic
from  .models.job_post_detail import JobPostDetails
from .models.job_applicant import JobApplicant
from userprofile.models.user_profile_basic import UserProfileBasic

from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from .forms import JobPostBasicForm,JobPostDetailsForm




def indexView(request):
    return render(request, 'jobpost/job_post_dashboard.html')

def listView(request):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    return render(request,'jobpost/job_post_dashboard.html',{'job_list':JobPostBasic.objects.get_job_title(),'userbasic':user_type, 'basic_user':user.id})

def detailJobView(request,id):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)

    basic = get_object_or_404(JobPostBasic, id=id)
    detail = get_object_or_404(JobPostDetails,id=id)
    try:
        applicant_object = JobApplicant.objects.get_job_applicant(id,user.id)
        status = True
    except:
        status = False
    return render(request,'jobpost/jobpostbasic_detail.html',{'basic':basic,'detail':detail,'status':status,'userbasic':user_type, 'basic_user':user.id})

def createJobView(request,id):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    if request.method == 'POST':
        basic_form = JobPostBasicForm(request.POST)
        detail_form = JobPostDetailsForm(request.POST)


        if all([basic_form.is_valid(), detail_form.is_valid()]):
            basic_job_post = basic_form.save(commit=False)
            basic_job_post.organization = user
            basic_job_post.save()
            details_job_post = detail_form.save(commit=False)
            details_job_post.job = basic_job_post
            details_job_post.save()

            return redirect('jobpost:detail',id=basic_job_post.id)
    else:
        basic_form = JobPostBasicForm()
        detail_form = JobPostDetailsForm()
    return render(request, 'jobpost/job_post_create.html', {'basic_form': basic_form, 'detail_form': detail_form,'user':user,'userbasic':user_type, 'basic_user':user.id})


def updateView(request,id):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    basic_object = get_object_or_404(JobPostBasic,id=id)
    detail_object = get_object_or_404(JobPostDetails,id=id)
    if request.method == 'POST':
        print(id)
        basic_form = JobPostBasicForm(request.POST,instance=basic_object)
        detail_form = JobPostDetailsForm(request.POST,instance=detail_object)
        if all([basic_form.is_valid(), detail_form.is_valid()]):
            basic_job_post = basic_form.save(commit=False)
            basic_job_post.organization = user
            basic_job_post.save()
            details_job_post = detail_form.save(commit=False)
            details_job_post.job = basic_job_post
            details_job_post.save()

            return redirect('jobpost:detail',id=id)
    else:
        basic_form = JobPostBasicForm(instance=basic_object)
        detail_form = JobPostDetailsForm(instance=detail_object)

    return render(request, 'jobpost/job_post_edit.html', {'basic_form': basic_form, 'detail_form': detail_form,'userbasic':user_type, 'basic_user':user.id})

def deleteView(request,id):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    basic_object = get_object_or_404(JobPostBasic,id=id)
    basic_object.status = False
    basic_object.save()
    return render(request,'jobpost/job_post_dashboard.html',{'job_list':JobPostBasic.objects.job_title(),'userbasic':user_type, 'basic_user':user.id})

def myJobView(request,id):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    job_list = JobPostBasic.objects.get_my_job(id)
    all_job = JobPostBasic.objects.get_job_title()
    print(job_list)
    return render(request,'jobpost/my_job_list.html',{'job_list':job_list,'all_job':all_job,'userbasic':user_type,'basic_user':user.id})

def jobApplyView(request,id):
    user=request.user
    obj, created = JobApplicant.objects.update_or_create(applicant_id=user.id,job_id=id,apply_status=True)
    print(obj.apply_status)
    return redirect('jobpost:detail',id=id)

def myAppliedJob(request):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    applied_job = JobApplicant.objects.get_applied_job(user.id)
    return render(request, 'jobpost/my_applied_job.html',{'job_list':applied_job,'userbasic':user_type, 'basic_user':user.id})

def myApplicantView(request,id):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    job_list = JobPostBasic.objects.get_my_job(user.id)
    print(job_list)
    return render(request,'jobpost/my_applicant_list.html',{'job_list':job_list,'userbasic':user_type, 'basic_user':user.id})

def myApplicantList(request,id):
    user = request.user
    user_type = UserProfileBasic.objects.get_organization_status(request.user.id)
    applicant_list = JobApplicant.objects.get_applicant_list(id)
    return render(request,'jobpost/applicant_list.html',{'applicant_list':applicant_list,'userbasic':user_type, 'basic_user':user.id})

templates/jobpost/applicant_list.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container-fluid">

    <!-- started event archive table -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Applicant Lists:
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th>User Name:</th>
                            <th>Details</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for single_applicant in applicant_list %}
                        <tr>
                            <td><a href="#" class="test-success"><span class="btn text-dark">{{ single_applicant.applicant }}</span></a></td>
                            <td><a href="/@{{ single_applicant.applicant }}/profile_details/{{ single_applicant.applicant_id }}" class="test-success"><span class="btn text-dark">Show Profile</span></a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <!--/.col-->
    </div>
    <!-- end event archive table -->

</div>
<!-- /.conainer-fluid -->


<br/><hr/>

{#<ul>#}
{#{% for obj in obj_list %}#}
{#    <li>{{ obj }}</li>#}
{#{% endfor %}#}
{#</ul>#}

{% endblock %}









<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {%for single_applicant in applicant_list%}
    {{single_applicant.applicant}}
    {%endfor%}

  </body>
</html> -->

templates/jobpost/job_list.html
{#{% extends 'base/base.html' %}#}
{##}
{#{% block content %}#}
{##}
{##}
{#    <h1>Job List</h1>#}
{##}
{#    {% for jobapplicant in jobapplicant_list %}#}
{#        <h2>{{ jobapplicant.applicant_id.get_full_name }}</h2>#}
{#        <h2>{{ jobapplicant.job_id.job_title }}</h2>#}
{#         <a href="{{ jobapplicant.job_id.get_absolute_url}}" class="btn btn-primary">Details</a>#}
{##}
{#    {% endfor %}#}
{##}
{##}
{##}
{#{% endblock %}#}


{% extends 'base/base.html' %}

{% block content %}

<div class="container-fluid">

    <!-- started event archive table -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Applicant List
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Job Title</th>
                            <th>Details</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for jobapplicant in jobapplicant_list %}
                        <tr>
                            <td><a href="{{ jobapplicant.get_absolute_url }}" class="test-success"><span class="btn text-dark">{{ jobapplicant.applicant_id.get_full_name }}</span></a></td>
                            <td class="text-center">
                                <a href="#" class="btn ">{{ jobapplicant.job_id.job_title }}</a>
                            </td>
                        <td><a href="#" class="test-success"><span class="btn text-dark">Details</span></a></td>
                        <td>
                            <div class="form-check">
                             <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                                <label class="form-check-label" for="defaultCheck1">
                                 Selection
                                </label>
                            </div>

                        </td>
                        <td>
                            <div class="form-check">
                             <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                                <label class="form-check-label" for="defaultCheck1">
                                 Call Interview
                                </label>
                            </div>

                        </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <nav>
                        <ul class="pagination">
                            <li class="page-item"><a class="page-link" href="#">Prev</a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">2</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">4</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!--/.col-->
    </div>
    <!-- end event archive table -->

</div>
<!-- /.conainer-fluid -->


<br/><hr/>

{#<ul>#}
{#{% for obj in obj_list %}#}
{#    <li>{{ obj }}</li>#}
{#{% endfor %}#}
{#</ul>#}

{% endblock %}

templates/jobpost/job_post_create.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Create Job Post</strong>
                </div>
                <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                    {% csrf_token %}
                    <div class="card-block">
                        {#  {{ form.as_p }}#}
{#                        {% if form.non_field_errors %}#}
{#                            <div class="alert alert-danger" role="alert">#}
{#                                {% for error in form.non_field_errors %}#}
{#                                    {{ error }}#}
{#                                {% endfor %}#}
{#                            </div>#}
{#                        {% endif %}#}

                        {% for field in basic_form.visible_fields %}
                            <div class="form-group row">
                                <label for="{{ field.auto_id }}" class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                                {% if form.is_bound %}
                                    {% if field.errors %}
                                         {% render_field field class="form-control is-invalid" %}
                                        {% for error in field.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                            {% render_field field class="form-control is-valid" %}
                                    {% endif %}
                                {% else %}
                                   <div class="col-md-6">
                                     {% render_field field class="form-control" %}
                                   </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        {% for field in detail_form.visible_fields %}
                            <div class="form-group row">
                                <label for="{{ field.auto_id }}" class="col-md-3 col-form-label">{{ field.label_tag }}</label>
                                {% if form.is_bound %}
                                    {% if field.errors %}
                                         {% render_field field class="form-control is-invalid" %}
                                        {% for error in field.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                            {% render_field field class="form-control is-valid" %}
                                    {% endif %}
                                {% else %}
                                   <div class="col-md-6">
                                     {% render_field field class="form-control" %}
                                   </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                        <button type="submit" name="save-event" class="btn btn-sm btn-primary"><i
                                class="fa fa-dot-circle-o"></i> Publish
                        </button>
                        <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--/.row-->

{% endblock %}







<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form  method="POST">
      {% csrf_token %}
      {{ basic_form.as_p }}
      {{ detail_form.as_p }}

      <input type="submit" name="" value="Submit">

    </form>

  </body>
</html> -->

templates/jobpost/job_post_dashboard.html
{% extends 'base/base.html' %}

{% block content %}


    <h1>Job List</h1>

{#    {% if job_list %}#}
{#    <ul>#}
{##}
{#      {% for job in job_list %}#}
{#      <li>#}
{#        <a href="{%url 'jobpost:detail' id=item.id%}">{{ job.job_title }}</a> {{ job.position }}#}
{#      </li>#}
{#          <li>#}
{#            <h2>{{ job.salary_range }}</h2>#}
{#            <h2>{{ job.deadline}}</h2>#}
{#        </li>#}
{#      {% endfor %}#}
{##}
{#    </ul>#}
{#    {% else %}#}
{#      <p>There are no books in the library.</p>#}
{#    {% endif %}#}

    {% if job_list %}
         {% for job in job_list %}
    <div class="card">
        <div class="card-header">
           <h3>{{ job.job_title }}</h3>
        </div>
        <div class="card-body">
            <h5 class="card-title"> Vacancy: {{ job.vacancy }}</h5>
            <p class="card-text"> Deadline: {{ job.deadline }}</p>
            <a href="{%url 'jobpost:detail' id=job.id%}" class="btn btn-primary">Details</a>
        </div>
    </div>
        {% endfor %}
    {% endif %}

{% endblock %}








<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to DashBoard</h1>
    <h3> <a href="{%url 'jobpost:create'%}">CREATE JOB POST</a> </h3>
    <p>
        {% for item in job_list%}
        <a href="{%url 'jobpost:detail' id=item.id%}">
          {{item.job_title}}
          {{item.salary_range}}
        </a>

        <br>
        {% endfor %}
    </p>
  </body>
</html> -->

templates/jobpost/job_post_deshboard.html
{% extends 'base/base.html' %}

{% block content %}
    <H1>Jobs post home page</H1>
    <h3><a href="{% url 'create' %}">Job Post Create</a></h3>
    <h3><a href="{% url 'joblist' %}">Job List </a></h3>
{%  endblock %}

templates/jobpost/jobpostbasic_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

templates/jobpost/jobpostbasic_detail.html
{% extends 'base/base.html' %}

{% block content %}
{#   <h1>Job List</h1>#}
{##}
{#    <h1>{{ jobpostbasic.job_title }}</h1><br>#}
{#    <h1>{{ jobpostbasic.position }}</h1><br>#}
{#    <h1>{{ jobpostbasic.salary_range }}</h1><br>#}
{#    <h1>{{ jobpostbasic.stack }}</h1><br>#}
{#    <h1>{{ jobpostbasic.vacancy }}</h1><br>#}
{#    <h1>{{jobpostbasic.jobpostdetails.description }}</h1><br>#}
{#    <h1>{{jobpostbasic.jobpostdetails.application_process }}</h1><br>#}
{#    <h1>{{jobpostbasic.jobpostdetails.screening_details }}</h1><br>#}

    <div class="card">
        <div class="card-header">
            <h3>{{ basic.job_title }}</h3>
        </div>
        <div class="card-body">
            <h5 class="card-title"> {{ basic.position }}</h5>
            <p class="card-title">Vacancy: {{basic.vacancy }}</p>
            <p class="card-text">Stack: {{ basic.stack}}</p>
            <p class="card-text">Job Nature: {{ basic.is_part_time}}</p>
            <p class="card-text">Salary Range: {{ basic.salary_range }}</p>

            <p class="card-text">Description: {{ detail.description }}</p>
            <p class="card-text">Application Process: {{ detail.application_process }}</p>
            <p class="card-text">Screening Process: {{ detail.screening_details }}</p>

            <p class="card-text">Deadline: {{ basic.deadline }}</p>
            {% if  userbasic.is_organization %}
            <a href="{% url 'jobpost:delete' id=basic.id %}" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-danger">Delete</a>
            <a href="{% url 'jobpost:edit' id=basic.id %}" class="btn btn-primary">Update</a>
            {% else %}
            {%if  status is False %}
            <a href="{% url 'jobpost:job_apply' id=basic.id %}" onclick="return confirm('Are you sure apply this Job?');" class="btn btn-danger">Apply</a>
            {%endif%}
            {%endif%}
        </div>
    </div>


{% endblock %}










<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title></title>
  </head>
  <body>
    <h1>THis is me</h1>
    <h3>
        {{basic.job_title}}
        {{basic.salary_range}}
        {{basic.deadline}}
        {{detail.screening_details}}
    </h3>

    <h2> <a href="{% url 'jobpost:edit' id=basic.id %}">Update</a> </h2>

    <h3> <a href="{% url 'jobpost:delete' id=basic.id %}" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a> </h3>


  </body>
</html> -->

templates/jobpost/jobpostbasic_list.html
{% extends 'base/base.html' %}

{% block content %}


    <h1>Job List</h1>

    {% if jobpostbasic_list %}
         {% for job in jobpostbasic_list %}
    <div class="card">
        <div class="card-header">
            {{ job.position }}
        </div>
        <div class="card-body">
            <h5 class="card-title"> {{ job.job_title }}</h5>
            <p class="card-text">{{ job.jobpostdetails.description }}</p>
            <a href="{{ job.get_absolute_url}}" class="btn btn-primary">Details</a>
        </div>
    </div>
        {% endfor %}
    {% endif %}

{% endblock %}

templates/jobpost/my_applicant_list.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container-fluid">

    <!-- started event archive table -->
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Find Your Applicants According to Your Job Post
                </div>
                <div class="card-block">
                    <table class="table table-bordered table-striped table-sm text-center">
                        <thead>
                        <tr>
                            <th>Job Title</th>
                            <th>Applicant List</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for job in job_list %}
                        <tr>
                            <td><a href="#" class="test-success"><span class="btn text-dark">{{ job.job_title }}</span></a></td>
                            <td><a href="{% url 'jobpost:applicantlist' id=job.id %}" class="test-success"><span class="btn text-dark">Show Applicants list</span></a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <!--/.col-->
    </div>
    <!-- end event archive table -->

</div>
<!-- /.conainer-fluid -->


<br/><hr/>

{#<ul>#}
{#{% for obj in obj_list %}#}
{#    <li>{{ obj }}</li>#}
{#{% endfor %}#}
{#</ul>#}

{% endblock %}

templates/jobpost/my_job_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>MY Job List: </h1>
    {%for job in my_job%}
    {{ job.job_title }}
    <br>
    {%endfor%}
    <h1> All JObs : </h1>
    {% for job in all_job %}
    {{ job.job_title }}
    {{ job.organization_id}}
    {%endfor%}


  </body>
</html>